Update Regresion Tests to account for Floating Point Error
waynebhayes/SpArcFiRe pull request #52
Opened 2021-02-09 18:16 UTC by JohnEEnglish

Also updated some text instructions since we are now using 'setup.bash' not 'setup.sh'

2021-02-13 04:56 UTC, waynebhayes commented on regression-tests/convert-FITS_+_generate_fit_quality/convert-FITS_+_generate_fit_quality.sh
> +awk '{for(i=1;i<=NF;i++) if(abs($1 $2) > 1.0e-6) print "different"}' > /tmp/sPaRCfIrE_TCP1
On what system have you ever seen "abs" as a built-in function to awk? This won't work; plus you've put ($1 $2) without a minus sign between them.

To make it work, it's easy: add the following before the rest of the awk code:

function abs(a,b) { if(a>b) return a-b; else return b-a;}

2021-02-13 04:58 UTC, waynebhayes commented on regression-tests/convert-FITS_no_arguments/convert-FITS_no_argument.sh
> +abs(){
Oh. Um. This is a Bourne shell function, and won't affect anything inside awk. Have you actually tried running this regression test?

2021-02-13 04:59 UTC, waynebhayes requested changes
Does this actually run? I can't imagine it works; you need to define an abs() function *inside awk*, not in the Bourne shell. See my comment inside for details.

2021-02-14 00:30 UTC, JohnEEnglish commented
Sorry my internet is out, I'll make the change  When it comes back.

On Fri, Feb 12, 2021, 9:00 PM Professor Wayne B. Hayes, UC Irvine <
notifications@github.com> wrote:

> *@waynebhayes* requested changes on this pull request.
>
> Does this actually run? I can't imagine it works; you need to define an
> abs() function *inside awk*, not in the Bourne shell. See my comment
> inside for details.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/waynebhayes/SpArcFiRe/pull/52#pullrequestreview-589943810>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABZTUALJEU5NAUO76JGNQ33S6YBLFANCNFSM4XLPGWQQ>
> .
>

2021-02-16 21:34 UTC, closed without merging